### ISSUE TITLE
Touch Effects: full screen banner is auto-focused

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Demos-old#189] opened 2016-12-08 02:41 UTC
https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/toucheffects/

Auto-focusing the banner on page load means the site header is bypassed, which may disorientate users. Should probably just let it be in regular tab order after the site header

**Comment by sarvaje** [comment] 2016-12-22 00:50
@dstorey I think that this is the expected behavior, you have to choose if you have to use the demo in fullscreen or not.
I think that this could be confusing because this is a popup but it looks like a banner.
I've opened the issue in [EdgePortal](https://github.com/MicrosoftEdge/EdgePortal/issues/3007)

**Comment by sarvaje** [comment] 2016-12-22 23:56
This is not a problem anymore. We turn this demo into a 'ishtml: true' demo.
Closing!

**Closed as completed by sarvaje** 2016-12-22 23:56 UTC
Labels: a11y
